-- MySQL Script generated by MySQL Workbench
-- Wed Mar 16 15:19:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projectoDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projectoDB` ;

-- -----------------------------------------------------
-- Schema projectoDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectoDB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `projectoDB` ;

-- -----------------------------------------------------
-- Table `projectoDB`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectoDB`.`restaurant` ;

CREATE TABLE IF NOT EXISTS `projectoDB`.`restaurant` (
  `restaurant_id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(45) NULL DEFAULT NULL,
  `restaurant_address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`restaurant_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectoDB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectoDB`.`user` ;

CREATE TABLE IF NOT EXISTS `projectoDB`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL DEFAULT NULL,
  `user_address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectoDB`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectoDB`.`order` ;

CREATE TABLE IF NOT EXISTS `projectoDB`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_user_id` INT NOT NULL,
  `restaurant_restaurant_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_user1_idx` (`user_user_id` ASC) VISIBLE,
  INDEX `fk_order_restaurant1_idx` (`restaurant_restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_restaurant1`
    FOREIGN KEY (`restaurant_restaurant_id`)
    REFERENCES `projectoDB`.`restaurant` (`restaurant_id`),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `projectoDB`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectoDB`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectoDB`.`product` ;

CREATE TABLE IF NOT EXISTS `projectoDB`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NULL DEFAULT NULL,
  `product_price` INT NULL DEFAULT NULL,
  `restaurant_restaurant_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_restaurant1_idx` (`restaurant_restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_restaurant1`
    FOREIGN KEY (`restaurant_restaurant_id`)
    REFERENCES `projectoDB`.`restaurant` (`restaurant_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectoDB`.`order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectoDB`.`order_product` ;

CREATE TABLE IF NOT EXISTS `projectoDB`.`order_product` (
  `order_product_id` INT NOT NULL AUTO_INCREMENT,
  `order_product_quantity` INT NULL DEFAULT NULL,
  `product_product_id` INT NOT NULL,
  `order_order_id` INT NOT NULL,
  PRIMARY KEY (`order_product_id`),
  INDEX `fk_order_product_product1_idx` (`product_product_id` ASC) VISIBLE,
  INDEX `fk_order_product_order1_idx` (`order_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_product_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `projectoDB`.`order` (`order_id`),
  CONSTRAINT `fk_order_product_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `projectoDB`.`product` (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
